### ISSUE TITLE
Tasks not fetching for contacts created through fillForms

### ISSUE THREAD

**Issue by IreneAchola** [medic/cht-conf-test-harness#135]
**To Reproduce**
Basic steps to reproduce the behavior:

1. Household registration test case: [REF](https://github.com/medic/config-vhw/pull/103/checks?check_run_id=3536050133#step:6:1450) 
2. Display harness.state contacts on the console to view their properties

```
it(`Register household member with pregnancy should emit pregnancy registration task`, async () => {

    //add female head where pregnant = 'yes'
    const memberResult = await harness.fillContactForm('clinic', ...householdRegistration.femaleHeadMaleMember(['approx', 36], ['yes'], 'Jane Junior', 'no'));
    expect(memberResult.errors).to.be.empty;

    //harness.subject.pregnant = 'yes';
    //harness.subject.reported_date = harness.getNow();

    const expectedTasks = await harness.getTasks({ title: 'pregnancy.registration.title' });
    expect(expectedTasks.length).to.equal(1);
  });
```

3. Uncomment harness.subject new property definitions for a passing test
4. Display harness.state contacts on the console to view their properties

**What happened?**
Created new contacts by filling household registration forms:
```
Register household member with pregnancy should emit pregnancy registration task:

      AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.it (test/contact/clinic-create.spec.js:68:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**What did you expect?**
Expected to have 1 task for woman who is indicated as pregnant from the clinic create forms.

```
    ✓ Register household member with pregnancy should emit pregnancy registration task (1206ms)


  1 passing (1s)
```

**Config**
nools.rules

**Additional context**
On debugging, tasks are fetched only for the default contact(s). Added another patient to harness defaults to verify and the conditions check out for them too. 

Duplicate `patient`, add `"pregnant": "yes"` property, update the `reported_date` to now. 

```
{
...
  "ownedBySubject": false,
  "docs": [
    {
      "_id": "patient_id2",
      "name": "Patient Name2",
      "date_of_birth": "1990-01-01",
      "sex": "female",
      "reported_date": 1631029058000,
      "patient_id": "12346",
      "type": "person",
      "pregnant": "yes"    
      ...
    }
```
- Task will be emitted for this patient and the default subject if the additional harness.subject properties are set as shown in the test case above.

**Comment by kennsippell** [comment]
@IreneAchola  Debugging the test failure it appears that the task isn't being triggered because of [this line](https://github.com/medic/config-vhw/blob/63-registration-form-updates/rules.nools.js#L171). The contacts that are being created don't have a parent that is a health_center (their parent is a `clinic` (made by form) which has a parent of type `clinic` (family_id) which has a parent of type `health_center`).  This may be partial fallout from https://github.com/medic/cht-conf-test-harness/issues/105 - but also seems like a legit issue with your test logic.  As far as I can tell, there does not appear to be a novel bug here. I've committed a change to your branch which hopefully can illustrate the test issue.
