### ISSUE TITLE
Support for Core 4.1

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#204]

**Comment by kennsippell** [comment]
Hey @jkuester  - I'm wondering your opinion on this issue.  To support cht-core 4.1 in the harness, would there be any changes in your `enketo-service-refactor` branch or would the underlying code be identical?

**Comment by jkuester** [comment]
Ah here we are already...  The short answer is no, I do not believe there are any major differences to the Enketo functionality between `4.1` and `enketo-service-refactor`.  None of the [changes in that release](https://docs.communityhealthtoolkit.org/core/releases/4.1.0/) seem like they would affect config tests.  So,  IMO, it should be fine to test config for `4.1` with the `enketo-service-refactor`.  

That being said, it is worth reiterating that the current approach is unsustainable. I need to get https://github.com/medic/cht-core/issues/7462 addressed as soon as possible so that work done here in the harness can be focused on a go-forward solution instead of continuing to hack and patch....
